<?php

namespace AppBundle\Repository\UserMgr;

/**
 * ReviewerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewerRepository extends \Doctrine\ORM\EntityRepository
{
}
